image: xtity/docker-centos7-elixir-phoenix
env:
  - MIX_ENV=test
script:
  - mix clean
  # - yes | mix local.hex && yes | mix local.rebar
  # - mix deps.get
  # - mix test
  # - mix compile
  # - mix dialyzer
deploy:
  bash:
    script:
      - MIX_ENV=prod mix deps.get
      - npm install && brunch build
      # - MIX_ENV=prod PORT=4000 mix release
      - MIX_ENV=prod mix release
      # - yes | mix local.hex && yes | mix local.rebar && mix do deps.get && MIX_ENV=prod mix compile.protocols
      # - mix compile.protocols
      - ssh xtity@xtity.com
      - ssh xtity@xtity.com "if [ -e /usr/local/src/phoenix/current ]; then
          mv /usr/local/src/phoenix/current /usr/local/src/phoenix/bk_`date '+%Y%m%d%H%M%S'`;
        fi;
        mkdir /usr/local/src/phoenix/current;"
      - scp -r rel/*/*.tar.gz xtity@xtity.com:/usr/local/src/phoenix/current
      - ssh xtity@xtity.com 'tar zxvf /usr/local/src/phoenix/current/*.tar.gz -C /usr/local/src/phoenix/current/'
      - ssh xtity@xtity.com 'echo `/usr/local/src/phoenix/current/bin/deploy_phoenix stop`; PORT=4000 /usr/local/src/phoenix/current/bin/deploy_phoenix start'
    # when:
    #   branch: master






