image: xtity/deploy_phoenix
env:
  - MIX_ENV=test
script:
  - mix clean
  # - yes | mix local.hex && yes | mix local.rebar
  # - mix deps.get
  # - mix test
  # - mix compile
  # - mix dialyzer
publish:
  github:
    artifacts:
      - release
    repo: deploy_phoenix
    script:
      - make release
    tag: v$(cat VERSION)
    token: $$github_token
    user: xtity
    # when:
    #   branch: master
deploy:
  bash:
    script:
      - MIX_ENV=prod mix deps.get
      - npm install && brunch build
      # - MIX_ENV=prod PORT=4000 mix release
      - MIX_ENV=prod mix release
      # - yes | mix local.hex && yes | mix local.rebar && mix do deps.get && MIX_ENV=prod mix compile.protocols
      # - mix compile.protocols
      - ssh xtity@xtity.com
      - ssh xtity@xtity.com "if [ ! -e /usr/local/src/phoenix/app/rel/deploy_phoenix/releases/$(cat VERSION) ]; then
          mkdir -p /usr/local/src/phoenix/app/rel/deploy_phoenix/releases/$(cat VERSION);
        fi;"
      - scp -r rel/*/*.tar.gz xtity@xtity.com:/usr/local/src/phoenix/app/rel/deploy_phoenix/releases/$(cat VERSION)/deploy_phoenix.tar.gz
    # when:
    #   branch: master






