image: xtity/deploy-phoenix
env:
  - MIX_ENV=test
script:
  - mix clean
  - yes | mix local.hex && yes | mix local.rebar
  - mix deps.get
  # - mix test
  # - mix compile
  # - mix dialyzer
deploy:
  bash:
    script:
      - MIX_ENV=prod mix deps.get
      - npm install && brunch build
      # - MIX_ENV=prod PORT=4000 mix release
      - MIX_ENV=prod mix release
      # - yes | mix local.hex && yes | mix local.rebar && mix do deps.get && MIX_ENV=prod mix compile.protocols
      # - mix compile.protocols
      - tar -cvzf ../build.tar.gz .
      - ssh xtity@xtity.com
      # - ssh xtity@xtity.com "if [ ! -e /usr/local/src/phoenix/app/deploy_phoenix/rel/deploy_phoenix/releases/$(cat VERSION) ]; then
      #     mkdir -p /usr/local/src/phoenix/app/deploy_phoenix/rel/deploy_phoenix/releases/$(cat VERSION);
      #   fi;"
      # - scp -r rel/deploy_phoenix/*.tar.gz xtity@xtity.com:/usr/local/src/phoenix/app/deploy_phoenix/rel/deploy_phoenix/
      # - scp -r rel/deploy_phoenix/*.tar.gz xtity@xtity.com:/usr/local/src/phoenix/app/deploy_phoenix/deploy/
      - ssh xtity@xtity.com "
          cd /usr/local/src/phoenix/deploy_phoenix/;
          if [ -e /usr/local/src/phoenix/deploy_phoenix/deploy ]; then
            rm -rf /usr/local/src/phoenix/deploy_phoenix/deploy;
          fi;
          mkdir deploy;
        "
      - scp -r ../build.tar.gz xtity@xtity.com:/usr/local/src/phoenix/deploy_phoenix/deploy/
      - ssh xtity@xtity.com "
          cd /usr/local/src/phoenix/deploy_phoenix;
          tar -xvzf deploy/build.tar.gz -C deploy/;
          rm -rf deploy/build.tar.gz
          rm -rf bk;
          cp -a current bk;
          mv -f deploy current;
        "
      # - ssh xtity@xtity.com "if [ ! -e /usr/local/src/phoenix/app/deploy_phoenix/rel/deploy_phoenix/releases/$(cat VERSION) ]; then
    # when:
    #   branch: master

# publish:
#   github:
#     artifacts:
#       - release
#     repo: deploy_phoenix
#     script:
#       - make release
#     tag: v$(cat VERSION)
#     token: $$github_token
#     user: xtity
    # when:
    #   branch: master









