image: xtity/deploy-phoenix
env:
  - PHOENIX_APP_HOST_SERVER=xtity.com
  - PHOENIX_APP_OWNER=xtity
script:
  - mix clean
  - yes | mix local.hex && yes | mix local.rebar
  - mix deps.get
  - mix compile
  - mix dialyzer
  - mix test --trace
publish:
  github:
    script:
      - yes | mix local.hex && yes | mix local.rebar && npm install && npm install -g brunch && mix do deps.get && brunch build && mix phoenix.digest && MIX_ENV=prod mix release
      - ssh ${PHOENIX_APP_OWNER}@${PHOENIX_APP_HOST_SERVER} "
          cd /usr/local/src/phoenix/${PHOENIX_APP_NAME};
          if [ ! -e /usr/local/src/phoenix/${PHOENIX_APP_NAME}/.git ]; then
            git clone ${PHOENIX_APP_REPO};
            /bin/echo 'Cloned from '${PHOENIX_APP_REPO};
          fi;
          git checkout .;
          git pull origin master;
          /bin/echo 'New version is v`/bin/cat VERSION`';
          /bin/echo '`/bin/date --iso-8601=seconds` v`/bin/cat VERSION` released' >> /usr/local/app/phoenix/${PHOENIX_APP_NAME}/RELEASE_VERSIONS;
        "
      - tar -czf rel.tar.gz rel
      - /bin/echo 'Defaults !requiretty' >> /etc/sudoers
    artifacts:
      - rel.tar.gz
    tag: v$(cat VERSION)
    token: $$github_token
    user: ${PHOENIX_APP_OWNER}
    repo: ${PHOENIX_APP_NAME}
    when:
      branch: master
