image: xtity/deploy-phoenix
env:
  - MIX_ENV=test
script:
  - mix clean
  - yes | mix local.hex && yes | mix local.rebar
  - mix deps.get
  # - mix test
  # - mix compile
  # - mix dialyzer
deploy:
  bash:
    script:
      - ssh xtity@xtity.com "
          if [ ! -e /usr/local/src/phoenix/deploy_phoenix/VERSION ]; then
            cd /usr/local/src/phoenix;
            git clone $PHOENIX_APP_REPO;
          fi;
          cd /usr/local/src/phoenix/deploy_phoenix;
          git pull origin master;
        "
      # - MIX_ENV=prod mix deps.get
      # - npm install && brunch build
      # - MIX_ENV=prod mix release
      # - tar -czf ../build.tar.gz .
      # - ssh xtity@xtity.com
      # - ssh xtity@xtity.com "
      #     cd /usr/local/src/phoenix/deploy_phoenix/;
      #     if [ -e /usr/local/src/phoenix/deploy_phoenix/deploy ]; then
      #       rm -rf /usr/local/src/phoenix/deploy_phoenix/deploy;
      #     fi;
      #     mkdir /usr/local/src/phoenix/deploy_phoenix/deploy;
      #   "
      # - scp -r ../build.tar.gz xtity@xtity.com:/usr/local/src/phoenix/deploy_phoenix/deploy/
      # - ssh xtity@xtity.com "
      #     cd /usr/local/src/phoenix/deploy_phoenix/deploy;
      #     tar -xzf build.tar.gz;
      #     rm -rf build.tar.gz;
      #     cd /usr/local/src/phoenix/deploy_phoenix;
      #     rm -rf bk;
      #     cp -a current bk;
      #     rm -rf current;
      #     mv deploy current;
      #   "
    # when:
    #   branch: master

# publish:
#   github:
#     artifacts:
#       - release
#     repo: deploy_phoenix
#     script:
#       - make release
#     tag: v$(cat VERSION)
#     token: $$github_token
#     user: xtity
    # when:
    #   branch: master









